Added walls and mines resouces are matters now
TheBlek/Project-Enyo pull request #14
Opened 2020-12-05 10:57 UTC by TheBlek

2020-12-06 02:57 UTC, Novemb3r commented on Assets/Scripts/Building.cs
> +    public virtual int GetCost()
А почему они виртуальные? Они же просто возвращают переменную, в дочерних классах должна оверрайдится сама переменная, кажется

2020-12-06 03:08 UTC, TheBlek commented on Assets/Scripts/Building.cs
> +    public virtual int GetCost()
А разве переменная может оверрайдиться?

2020-12-06 03:12 UTC, Novemb3r requested changes

2020-12-06 03:12 UTC, ghost commented on Assets/Scripts/Building.cs
> +    public virtual int GetCost()
То есть, в Mine.cs GetCost имеет точно такую же реализацию

2020-12-06 03:12 UTC, Novemb3r commented on Assets/Scripts/GameManager.cs
> +        if (building.GetCost() <= metals)
`return building.GetCost() <= metals;`

2020-12-06 03:12 UTC, Novemb3r commented on Assets/Scripts/PlayerControls.cs
> +            building_num = 0;
Тут прям нужен enum, чтобы не запутаться потом
https://metanit.com/sharp/tutorial/2.12.php

2020-12-06 03:12 UTC, Novemb3r commented on Assets/Scripts/GameManager.cs
> +    public bool IsIntersectingWithBuildings(Bounds bounds)
Блен, это и IsIntersectingWithWalls тоже надо как то утащить в Builder, иначе логика постройки размазалась между Builder и GameManager

2020-12-06 12:12 UTC, Novemb3r commented on Assets/Scripts/Building.cs
> +    public virtual int GetCost()
Блен, шарп не умеет, тогда сделай как удобнее, либо через внешний параметр, как сейчас сделал, либо как было) Кстати, для гетеров есть прикольный сахар: https://stackoverflow.com/questions/5096926/what-is-the-get-set-syntax-in-c

2020-12-07 06:45 UTC, TheBlek commented
#12

2020-12-08 03:10 UTC, Novemb3r commented on Assets/Scripts/PlayerControls.cs
> +    public enum buildings
https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-classes-structs-and-interfaces#naming-enumerations

тут, по хорошему должно быть с большой буквы, csharp придерживается PascalCase

2020-12-08 03:28 UTC, Novemb3r approved these changes

2020-12-08 03:28 UTC, merged