Grid system
TheBlek/Project-Enyo pull request #30
Opened 2020-12-17 10:43 UTC by TheBlek

Damn boy grid system

2020-12-23 14:15 UTC, Novemb3r requested changes

2020-12-23 14:15 UTC, ghost commented on Assets/Scripts/Misc/GridCell.cs
> +        if (building_in_cell == null)
`return building_in_cell == null`

2020-12-23 14:15 UTC, ghost commented on Assets/Scripts/Misc/GridCell.cs
> +    private Building building_in_cell;
В шарпе есть хороший синтаксис для гетеров и сетеров: https://codeasy.net/lesson/properties

можно просто написать 
`private Building  building_in_cell {get, set}`

2020-12-23 14:15 UTC, ghost commented on Assets/Scripts/Buildings/Wall.cs
> +        name = "Wal";
А почему тут так?

2020-12-23 14:15 UTC, ghost commented on Assets/Scripts/Buildings/Wall.cs
> +        return name == "Wall" || name == "Gate";
Здесь лучше сравнивать с Enumом, что-нибудь вроде
`name == Buildings.Wall.ToString()`

2020-12-23 14:15 UTC, ghost commented on Assets/Scripts/Player/Builder.cs
> +    private bool IsBuildable(PlayerControls.Buildings building_type, Vector2 pos, GameManager gameManager)
Buildings лучше, наверное, вынести из PlayerControls просто в отдельный файл, тк он относится не только к PlayerControls

2020-12-23 14:15 UTC, ghost commented on Assets/Scripts/GameManager.cs
>      public List<Bounds> GetBuildingsBounds()
Кстати, а это используется где-то?

2020-12-23 14:15 UTC, ghost commented on Assets/Scripts/GameManager.cs
> +    private void InitGrid()
Работу с Grid бы вынести куда-нибудь, например в GridManager, как сделано с Builder, чтобы здесь не было этой логики

2020-12-23 14:15 UTC, ghost commented on Assets/Scripts/GameManager.cs
> +    public Building GetBuildingInCell(Vector2Int cell)
И вот это тоже бы уехало в CellManager

2020-12-24 04:07 UTC, TheBlek commented on Assets/Scripts/Buildings/Wall.cs
> +        name = "Wal";
Дело в том, что я делаю рекол соседей, когда стена умирает, но рекол происходит до уничтожения самой стены, поэтому у соседей не меняется текстура. Я вставил тут этот костыль, чтобы ее не идентифицировали, как стену перед смертью и соответственно меняли текстуру

2020-12-24 04:08 UTC, TheBlek commented on Assets/Scripts/GameManager.cs
>      public List<Bounds> GetBuildingsBounds()
Да, используется. В воротах и PlayerControls

2020-12-27 09:47 UTC, Novemb3r approved these changes

2020-12-27 09:47 UTC, merged